# Config for https://github.com/apps/release-drafter

name-template: 'v$NEXT_PATCH_VERSION'

tag-template: 'v$NEXT_PATCH_VERSION'

template: |
  ## What's new?

  $CHANGES

  All contributors: $CONTRIBUTORS
