# adapted from https://github.com/scikit-learn/scikit-learn/blob/master/.travis.yml

# use travis only on the following branches for building
branches:
    only:
        - master
        - dev

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sktime
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
    - PYTHON_VERSION="3.7" NUMPY_VERSION="1.16" SCIPY_VERSION="1.2" SKLEARN_VERSION="0.21" JOBLIB_VERSION="0.11"
      CYTHON_VERSION="0.29" PANDAS_VERSION="0.23" STATSMODELS_VERSION="0.9" SCIKIT_POSTHOCS_VERSION="0.5.0"

matrix:
    # platforms and package environments to test
    include:
        - os: osx

install:
    # install conda environment and build package
    - source build_tools/travis/install.sh

script:
    # run unit tests
    - bash build_tools/travis/test_script.sh

after_success:
    # generate website content
    - cd ../documentation
    - make html

deploy:
    # on master branch, deploy website and upload compiled files to Github
    - provider: pages
      skip-cleanup: true
      local_dir: "./documentation/build_doc_site/html"
      github-token: $GITHUB_TOKEN  # Generated in the settings page of your repository, as a secure variable
      keep-history: false
      on:
          branch: master
    - provider: releases
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      draft: true
      on:
          branch: master
          tags: true



