contact_links:
  - name: "All other questions and general chat"
    url: https://gitter.im/sktime/community
    about: Chat with the sktime community on Gitter
  - name: "Code of Conduct incident reporting"
    url: https://gitter.im/sktime/community
    about: Report an incident to the Code of Conduct committee
